// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: v1/hubble.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HubbleClient is the client API for Hubble service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HubbleClient interface {
	// 打招呼方法
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type hubbleClient struct {
	cc grpc.ClientConnInterface
}

func NewHubbleClient(cc grpc.ClientConnInterface) HubbleClient {
	return &hubbleClient{cc}
}

func (c *hubbleClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/proto.Hubble/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HubbleServer is the server API for Hubble service.
// All implementations must embed UnimplementedHubbleServer
// for forward compatibility
type HubbleServer interface {
	// 打招呼方法
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedHubbleServer()
}

// UnimplementedHubbleServer must be embedded to have forward compatible implementations.
type UnimplementedHubbleServer struct {
}

func (UnimplementedHubbleServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedHubbleServer) mustEmbedUnimplementedHubbleServer() {}

// UnsafeHubbleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HubbleServer will
// result in compilation errors.
type UnsafeHubbleServer interface {
	mustEmbedUnimplementedHubbleServer()
}

func RegisterHubbleServer(s grpc.ServiceRegistrar, srv HubbleServer) {
	s.RegisterService(&Hubble_ServiceDesc, srv)
}

func _Hubble_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubbleServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hubble/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubbleServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hubble_ServiceDesc is the grpc.ServiceDesc for Hubble service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hubble_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Hubble",
	HandlerType: (*HubbleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Hubble_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/hubble.proto",
}
